### ISSUE TITLE
Missing SOTA fusion results for training pseudo sensing module

### ISSUE THREAD

**Issue by zzowenzz** [Zhaozixiang1228/MMIF-EMMA#2]
Exciting work, and appreciate your open sourcing of the code. @Zhaozixiang1228 

Just wondering that, did you forget to upload the SOTA fusion results for training pseudo sensing module, which is listed in Line 18 of `dataprocessing/MSRS_AiAv.py`? It appears to point to two previous work from you(also excellent work by the way), which are the fusion results that used as SOTA so that the pseudo sensing module can be trained under the manner of supervised learning. 

And please correct me if I am wrong.

**Comment by Wei-1989** [comment]
Also eagerly looking forward to the SOTA fusion results
